/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
/* deno-fmt-ignore-file */
import "sst"
export {}
declare module "sst" {
  export interface Resource {
    "ApiKey": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "Bus": {
      "arn": string
      "name": string
      "type": "sst.aws.Bus"
    }
    "ObsPassword": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "ObsWebsocket": {
      "type": "sst.sst.Resource"
      "url": string
    }
    "Realtime": {
      "authorizer": string
      "endpoint": string
      "type": "sst.aws.Realtime"
    }
    "Service": {
      "type": "sst.aws.Service"
      "url": string
    }
    "SpotifyAccessToken": {
      "arn": string
      "id": string
      "type": "aws.secretsmanager/secret.Secret"
    }
    "SpotifyClientId": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "SpotifyClientSecret": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "SpotifyRefreshToken": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "StaticIpAddress": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "Table": {
      "name": string
      "type": "sst.aws.Dynamo"
    }
    "TerminalStripeSecret": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "TerminalStripeWebhook": {
      "id": string
      "secret": string
      "type": "stripe.index/webhookEndpoint.WebhookEndpoint"
    }
    "TwitchClientId": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "TwitchClientSecret": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "TwitchTokens": {
      "arn": string
      "id": string
      "type": "aws.secretsmanager/secret.Secret"
    }
    "TwitchUserId": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "VpcV2": {
      "type": "sst.aws.Vpc"
    }
  }
}
